version: "3.4"
services:
  elide_test:
    container_name: "elide_test"
    build:
      context: .
      dockerfile: "Dockerfile.test"
      cache_from:
        - rust:latest
    links:
      - "postgres"
    depends_on:
      - "postgres"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/elide
    networks:
      - elide_test
    volumes:
      - ./:/app
    tty: true
    ports:
      - "9600:9600"

  postgres:
    image: postgres:alpine
    volumes:
      - pg_actix:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGPASSWORD: "${PGPASSWORD}"
    networks:
      - elide_test
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    networks:
      - elide_test
    ports:
      - "6379:6379"

networks:
  elide_test:
    driver: bridge

volumes:
  pg_actix:
    driver: local
